######################################################################
# Lockdown Apache Playbook
######################################################################
# This playbook locks down the network:
# 	allow ssh from mgmt node
#   allow tcp/80 from haproxy/mgmt nodes
# 	block all other unused/unnecessary ports
---
# UFW Configuration for Apache nodes
- name: Allow SSH tcp/22 from mgmt node
  ufw:
    rule: allow
    interface: eth0
    direction: in
    from_ip: $IP
    port: '22'
    proto: tcp

- name: Allow tcp/80 from haproxy node
  ufw:
    rule: allow
    interface: eth0
    direction: in
    from_ip: $IP
    to_port: '80'
    proto: tcp

- name: Allow tcp/80 from mgmt node
  ufw:
    rule: allow
    interface: eth0
    direction: in
    from_ip: $IP
    to_port: '80'
    proto: tcp

- name: Allow tcp/443 for apt-get
  ufw:
    rule: allow
    port: '443'
    proto: tcp
    direction: out

- name: Allow tcp/80 for apt-get
  ufw:
    rule: allow
    port: '80'
    proto: tcp
    direction: out

- name: Allow outgoing DNS for apt-get
  ufw:
    rule: allow
    port: '53'
    direction: out

# Enable UFW with default reject rule    
- name: Enable and reject all other traffic
  ufw: 
    state: enabled 
    policy: reject