######################################################################
# Apache Role Handlers
######################################################################
---
- name: Start Apache
  service: 
    name: apache2 
    state: started 
    enabled: yes

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  