# Playbook to import existing configration file
---
- name: Import configuration file into PAN-OS
  hosts: pan01
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    config_file: "/Users/jd/Projects/ansible/playbooks-pan/running-config_export01.xml"

  tasks:
  # get credentials
  - name: grab credentials Ansible Vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  # import
  - name: import configuration file into PAN-OS
    panos_import:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      file: "{{ config_file }}"
      category: "configuration"